import React from 'react'

const About = () => {

  React.useEffect(() => {
    document.title = 'PrintZInk - ABOUT';
  }, []);



  return (
    <section>
      <div className='container'>
      <h1>About</h1>
      <p><strong>SINCE 2022, WE WORK IN THE CUSTOMIZATION SEGMENT. FROM BRAND CREATION TO FINAL PRODUCT DELIVERY. WITHIN THIS BRANCH, WE OFFER TWO TYPES OF SERVICES TO OUR CUSTOMERS:
PRIVATE LABEL: WE DEVELOP PRODUCTS FOR SMALL AND LARGE BRANDS IN THE FASHION BUSINESS.<br/>
UNITS: WE SERVE SMALL, MEDIUM AND LARGE COMPANIES.
WE HAVE PROFESSIONAL MANAGEMENT, THAT CONTROLS ITS PRODUCTION PROCESS AND WORKS WITH RESPONSIBILITY AND TRANSPARENCY.<br/>
WE PROPOSE A COMMITMENT TO QUALITY, ALWAYS LOOKING FOR INNOVATION AND IMPROVEMENTS FOR OUR TEAM AND CUSTOMERS IN ORDER TO DELIVER THE BEST EXPERIENCE WITH OUR PRODUCTION.
AT PRINTZ WE DEVELOP QUALITY PRODUCTS AND ALWAYS WITH THE AIM TO EXCEED OUR CLIENTS' EXPECTATIONS. PRINTING YOUR IDEA HAS NEVER BEEN EASIER.</strong></p>
      </div>

    </section>
  )
}

export default About